version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tectonic_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  frontend:
    build: ./frontend
    container_name: tectonic_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000
      - GENERATE_SOURCEMAP=false
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  generated_data:
  node_modules:

networks:
  default:
    name: tectonic_network